input_dir: "data/input"
output_dir: "data/output"
reliability_fraction: 0.2
coders: [XX, YY, ZZ]

tiers:
  "*site": [AC, BU, TU]
  test: [Pre, Post, Maint]
  participantID: "site##"
  narrative:
    - CATGrandpa
    - BrokenWindow
    - RefusedUmbrella
    - CatRescue
    - BirthdayScene
