from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQS = ROOT / "reqs"


def test_requirement_splits_are_present() -> None:
    expected = {"base", "dev", "asr", "nlp", "full"}

    assert {path.stem for path in REQS.glob("*.in")} == expected
    assert {path.stem for path in REQS.glob("*.txt")} == expected


def test_requirement_inputs_resolve_diaad_from_project_metadata() -> None:
    expected_inputs = {
        "base.in": ["-e ."],
        "dev.in": ["-e .[dev]"],
        "asr.in": ["-e .[asr]"],
        "nlp.in": ["-e .[nlp]"],
        "full.in": ["-e .[dev,asr,nlp]"],
    }

    for filename, expected_lines in expected_inputs.items():
        actual_lines = (REQS / filename).read_text(encoding="utf-8").splitlines()
        assert actual_lines == expected_lines


def test_compiled_requirements_record_pip_compile_command() -> None:
    for input_file in REQS.glob("*.in"):
        output_file = input_file.with_suffix(".txt")
        contents = output_file.read_text(encoding="utf-8")

        assert "This file is autogenerated by pip-compile with Python 3.12" in contents
        assert (
            f"pip-compile --no-build-isolation --output-file=reqs/{input_file.stem}.txt "
            f"reqs/{input_file.name}"
        ) in contents


def test_compiled_requirements_do_not_require_sibling_diaad_checkout() -> None:
    for requirements_file in REQS.glob("*.txt"):
        contents = requirements_file.read_text(encoding="utf-8")
        assert "../DIAAD" not in contents
